services:
  voicememobot:
    image: ghcr.io/sgzmd/voicememobot:latest
    container_name: voicememobot
    command: ["--config", "/root/config.yaml"]
    volumes:
      - ./config.yaml:/root/config.yaml
      - ./key.json:/root/key.json